import sqlite3 as sql
conn=sql.connect('aquarium.db')
conn.execute("Create table FISH (tank INTEGER,name TEXT,species TEXT, age INTEGER)")
conn.execute("INSERT into FISH values(1,'Mahesh','Goldfish',10)")
conn.execute("INSERT into FISH values(1,'Abhiram','Clownfish',8)")
conn.execute("INSERT into FISH values(2,'Omkar','Stingray',9)")
conn.execute("INSERT into FISH values(2,'Nitish','Mantleray',9)")
conn.execute("INSERT into FISH values(3,'Vinay','Jellyfish',5)")
conn.commit()
conn.close()