a=float(input("Enter number 1 value"))
b=float(input("Enter number 2 value"))
print("The sum is ", a+b)
print("The difference is ", a-b)
print("The product is ", a*b)
print("The quotient is ", a/b)
print("The remainder is ", a%b)
