a=int(input("Enter integer value"))
b=float(input("Enter float value"))
print("Addition - ", a+b)
print("Sbtraction - ", a-b)
print("Multiplication - ", a*b)
print("Division - ", a/b)
print("Floor Division - ", a//b)
print("Modulus - ", a%b)
print("Exponent - ", a**b)

