a=int(input("Enter number 1 value"))
b=int(input("Enter number 2 value"))
print("Addition - ", a+b)
print("Sbtraction - ", a-b)
print("Multiplication - ", a*b)
print("Division - ", a/b)
print("Floor Division - ", a//b)
print("Modulus - ", a%b)
print("Exponent - ", a**b)

